In [1]:
import pandas as pd
from dfply import *

In [2]:
diamonds.head(3)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [3]:
diamonds >> head(3)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [4]:
diamonds[['carat','color','depth']].head(2)

carat color  depth
0   0.23     E   61.5
1   0.21     E   59.8

In [5]:
diamonds >> select(X.carat, 'color', 4) >> head(2)

carat color  depth
0   0.23     E   61.5
1   0.21     E   59.8

In [7]:
diamonds >> row_slice([1,2,3,6])

carat        cut color clarity  depth  table  price     x     y     z
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47

In [9]:
diamonds >> groupby(X.cut) >> row_slice([1,3])

carat        cut color clarity  depth  table  price     x     y     z
91    0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
123   0.70       Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
4     0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
17    0.30       Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
11    0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
16    0.30      Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
3     0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
14    0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
6     0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
9     0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [10]:
diamonds >> groupby(X.cut) >> mutate(price_lag1=X.price.shift(1)) >> head(2) >> ungroup()

carat        cut color clarity  depth  table  price     x     y     z  \
8    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49   
91   0.86       Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52   
2    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
4    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
0    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46   
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48   
6    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47   

    price_lag1  
8          NaN  
91       337.0  
2          NaN  
4        327.0  
0          NaN  
11       326.0  
1          NaN  
3        326.0  
5          NaN  
6        336.0

In [11]:
diamonds >> select(X.color, X.clarity, X.table) >> gather('variable','value') >> head(10)

variable value
0    color     E
1    color     E
2    color     E
3    color     I
4    color     J
5    color     J
6    color     I
7    color     H
8    color     E
9    color     H

In [ ]:
data = DplyFrame(diamonds)

In [12]:
from functools import wraps

In [18]:
def my_decorator(function):
    @wraps(function)
    def wrapped_function(*args, **kwargs):
        print 'inside wrapped function', args, kwargs
        return function(*args, **kwargs)
    return wrapped_function

In [19]:
@my_decorator
def add_function(a,b, c='keyword argument'):
    print 'inside add_function'
    return a+b

In [20]:
add_function(1,2)

inside wrapped function (1, 2) {}
inside add_function


3

In [21]:
@Pipe
@GroupDelegation
@SymbolicEvaluation
def myhead(df, n=1):
    print df.head(1)

In [22]:
diamonds >> myhead(1)

   carat    cut color clarity  depth  table  price     x     y     z
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43


ValueError: setting an array element with a sequence.

In [36]:
np.array([[1],[2,3]]).ravel()

array([[1], [2, 3]], dtype=object)

In [38]:
hasattr(np.array(1), '__iter__')

True

In [39]:
np.array(1)

array(1)

In [40]:
np.atleast_1d(1)

array([1])

In [41]:
np.atleast_1d([1,2])

array([1, 2])

In [50]:
def f(*args):
    print args
    
f(np.array([1,2,3,4]))

(array([1, 2, 3, 4]),)


In [ ]:
reduce()